import type { Metadata } from "next";
import {ThemeProvider} from "@mui/system";
import './globals.css';
import theme from '../theme';
import MDHeader from "@/app/components/MD-Header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={'bg-base-back w-screen h-screen'}>
          <ThemeProvider theme={theme}>
              <MDHeader />
              {children}
          </ThemeProvider>
      </body>
    </html>
  );
}
